@startuml C4_Component
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Container_Boundary(ms_transfers, "Microservicio de Transferencias") {
    Component(api_controller, "Transfer Controller", "REST API", "Recibe peticiones de API Gateway y valida DTOs")
    Component(transfer_service, "Transfer Service", "Lógica de Negocio", "Aplica reglas de negocio (fondos suficientes, límites)")
    Component(core_integration, "Core Integration Client", "Adapter", "Maneja la comunicación y reintentos (Circuit Breaker) con el Core")
    Component(event_publisher, "Event Publisher", "Messaging", "Formatea y envía mensajes al bus de eventos")
}

Container(api_gateway, "API Gateway", "AWS API Gateway")
System_Ext(core_banking, "Plataforma Core", "Sistema heredado")
Container(event_bus, "Bus de Eventos", "AWS EventBridge")

Rel(api_gateway, api_controller, "POST /api/v1/transfers")
Rel(api_controller, transfer_service, "Llama métodos")
Rel(transfer_service, core_integration, "Solicita ejecución de débito/crédito")
Rel(transfer_service, event_publisher, "Informa transacción exitosa")

Rel(core_integration, core_banking, "Ejecuta transacción [HTTPS]")
Rel(event_publisher, event_bus, "Publica TransferCompletedEvent")
@enduml